using LendingPlatform.DomainModel.Enums;
using System;
using System.Collections.Generic;

namespace LendingPlatform.Repository.ApplicationClass.Others
{
    public class AuditLogAC
    {
        /// <summary>
        /// Unique audit LogId.
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// Table name that operation perform on the table.
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// Action like "Insert", "Update" or "Delete"
        /// </summary>
        public string Action { get; set; }
        /// <summary>
        /// Json object for the table details.
        /// </summary>
        public string AuditJson { get; set; }
        /// <summary>
        /// List of fields of the table. It contains old value and new value of the field.
        /// </summary>
        public List<AuditLogFieldAC> AuditLogFields { get; set; }
        /// <summary>
        /// Created date of the log.
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// If it's true when log generated by the bank user else false.
        /// </summary>
        public bool IsBankUser { get; set; }
        /// <summary>
        /// UserId of the who generates the log.
        /// </summary>
        public Guid? CreatedByUserId { get; set; }
        /// <summary>
        /// User name of the generated log.
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// User email of the generated log.
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Primary key of the audit log table.
        /// </summary>
        public Guid TablePk { get; set; }
        /// <summary>
        /// Ip address of the user.
        /// </summary>
        public string IpAddress { get; set; }
        /// <summary>
        /// It uses to fetch the block wise record.
        /// eg. Company and loan application.
        /// </summary>
        public ResourceType LogBlockName { get; set; }
        /// <summary>
        /// LoanId or EntityId. It's use to fetch the block wise log details of the loan or entity.
        /// </summary>
        public Guid? LogBlockNameId { get; set; }
        /// <summary>
        /// It's used to show old value in the dialogue.
        /// </summary>
        public bool IsShowOldValue { get; set; }
    }
}
